version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: podcast-api
    container_name: podcast-api-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    networks:
      - podcast-network
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: podcast-api-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql/
    networks:
      - podcast-network

  nginx:
    image: nginx:alpine
    container_name: podcast-api-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - podcast-network
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: podcast-api-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - podcast-network

networks:
  podcast-network:
    driver: bridge

volumes:
  mysql:
    driver: local